[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe" # Use LLD Linker
rustflags = [
  "-Zshare-generics=n", # (Nightly)
  "-Zthreads=0",        # (Nightly) Use improved multithreading with the recommended amount of threads.
]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[build]
rustflags = [ "--cfg=web_sys_unstable_apis" ]
rustdocflags = [ "--cfg=web_sys_unstable_apis" ]